openapi: "3.0.2"
info:
  title: Comps Engine - External Integrations
  version: "1.0.0"
servers:
  - url: 'http://localhost:9000'
    description: Local Gateway.
  - url: "https://gateway.lithium-develop.ls-g.net"
    description: Livescore Lithium Develop
  - url: "https://gateway.lithium-qa.ls-g.net"
    description: Livescore Lithium QA
  - url: "https://gateway.lithium-staging.ls-g.net/"
    description: Livescore Lithium Staging
  - url: "https://gateway.lithium-prod.ls-g.net"
    description: Livescore Lithium Production
tags:
  - name: Promotions
    description: These endpoints relate to promotions.

paths:
  /service-promo/external/find-promotions:
    get:
      tags:
        - Promotions
      description: |
        Obtain a list of promotions that are exclusive that can be used in the
        add players endpoint.
      security:
        - BasicTokenAuth: []
      parameters:
        - name: domainName
          required: true
          allowEmptyValue: false
          in: query
          schema:
            type: string
          description: |-
            The registered brand to use to find promotions available.
          example: livescore_uk
        - name: sha256
          required: true
          allowEmptyValue: false
          in: query
          schema:
            type: string
          description: |
            The hash needs to be calculated using the domainName as key along with a preSharedKey provided by the lithium team.
            
            **Example:**
            
            If domainName = "livescore_uk" and preSharedKey = "abcdefg123"
            - then key = "livescore_uk"
            - and hmac_sha256(key, preSharedKey) = "9c25dc588496932134504bd219c4c23583b373aa22b7f50c82a0f1070bd83079"
          example: 9c25dc588496932134504bd219c4c23583b373aa22b7f50c82a0f1070bd83079
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PromotionExt"

  /service-promo/external/add-players:
    post:
      tags:
        - Promotions
      description: |
        Can be used to add individual players to an exclusive promotion.
      security:
        - BasicTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExclusiveUploadRequest"
      responses:
        "200":
          description: Successfully executed, response contains details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExclusiveUploadProgress"
        "411":
          description: Invalid promotion provided.
        "431":
          description: Invalid sha provided.

  /service-promo/external/remove-players:
    post:
      tags:
        - Promotions
      description: |
        Can be used to remove individual players from an exclusive promotion.
      security:
        - BasicTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExclusiveUploadRequest"
      responses:
        "200":
          description: Successfully executed, response contains details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExclusiveUploadProgress"
        "411":
          description: Invalid promotion provided.
          content:
            application/json:
              example:
                message: Invalid promotion provided
                status: 411
                error: errorcodeexception_411
                error_description: Invalid promotion provided
                exception: lithium.service.promo.client.exception.Status411InvalidPromotionException
                errorCode: lithium.service.promo.client.exception.Status411InvalidPromotionException
        "470":
          description: Invalid sha provided.
          content:
            application/json:
              example:
                message: Invalid hash
                status: 470
                error: errorcodeexception_470
                error_description: Invalid hash
                exception: lithium.exceptions.Status470HashInvalidException
                errorCode: lithium.exceptions.Status470HashInvalidException
  /service-promo/external/{promoExclusiveUploadId}/progress:
    get:
      tags:
        - "Promotions"
      description: |
        Can be used to retrieve the exclusive list upload progress.
      parameters:
        - in: path
          name: promoExclusiveUploadId
          schema:
            type: integer
          required: true
          description: The id of the upload record to retrieve
        - in: query
          name: sha256
          schema:
            type: string
          required: true
          description: |
            The hash needs to be calculated using the promoExclusiveUploadId as key along with a preSharedKey provided by the lithium team.
            
              **Example:**
            
              If promoExclusiveUploadId = "12" and preSharedKey = "abcdefg123"
              - then key = "12"
              - and hmac_sha256(key, preSharedKey) = "9c25dc588496932134504bd219c4c23583b373aa22b7f50c82a0f1070bd83079"

      security:
        - BasicTokenAuth: []
      responses:
        "200":
          description: Successfully executed, response contains details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExclusiveUploadProgress"
        "411":
          description: Invalid promotion provided.
          content:
            application/json:
              example:
                message: Invalid promotion provided
                status: 411
                error: errorcodeexception_411
                error_description: Invalid promotion provided
                exception: lithium.service.promo.client.exception.Status411InvalidPromotionException
                errorCode: lithium.service.promo.client.exception.Status411InvalidPromotionException
        "412":
          description: Invalid upload id.
          content:
            application/json:
              example:
                message: An invalid exclusive upload id was provided
                status: 412
                error: errorcodeexception_412
                error_description: An invalid exclusive upload id was provided
                exception: lithium.service.promo.client.exception.Status412InvalidExclusiveUpload
                errorCode: lithium.service.promo.client.exception.Status412InvalidExclusiveUpload
        "470":
          description: Invalid sha provided.
          content:
            application/json:
              example:
                message: Invalid hash
                status: 470
                error: errorcodeexception_470
                error_description: Invalid hash
                exception: lithium.exceptions.Status470HashInvalidException
                errorCode: lithium.exceptions.Status470HashInvalidException
components:
  schemas:
    PromotionExt:
      type: object
      properties:
        id:
          type: number
          format: int64
          example: 1
          description: Identifier for the promotion revision.
        name:
          type: string
          example: Welcome Offer - June
        description:
          type: string
          example: When signing up in June receive $$$
    ExclusiveUploadRequest:
      type: object
      properties:
        promotionId:
          type: number
          format: int64
          example: 1
          description: Identifier for the promotion revision.
        players:
          type: array
          items:
            type: string
            example: livescore_uk/riaansuk
        sha256:
          type: string
          description: |
            The hash needs to be calculated using the promotionId as key along with a preSharedKey provided by the lithium team.
            
            **Example:**
            
            If promotionId = "12" and preSharedKey = "abcdefg123"
            - then key = "12"
            - and hmac_sha256(key, preSharedKey) = "9c25dc588496932134504bd219c4c23583b373aa22b7f50c82a0f1070bd83079"
          example: 9c25dc588496932134504bd219c4c23583b373aa22b7f50c82a0f1070bd83079
    ExclusiveUploadProgress:
      type: object
      properties:
        promoExclusiveUploadId:
          type: number
          example: 1
        uploadType:
          type: string
          example: add
          description: |
            available types [add, remove]
        uploadStatus:
          type: string
          example: uploading
          description: |
            The status of the upload,
            available statuses [created, uploading, failed, done]
        processedPlayers:
          type: number
          example: 0
        totalPlayers:
          type: number
          example: 14353
        invalidPlayers:
          type: number
          example: 0
        validPlayers:
          type: number
          example: 0